version: '3.7'

services:
  api:
    build:
      context: .
    container_name: lab_6
    working_dir: /app
    restart: unless-stopped
    networks:
      lab:
        aliases:
          - target
    ports:
      - '3000:3000'

    volumes:
      - ./:/app
      - /app/node_modules
  kali:
    build:
      context: ./kali
    container_name: kali
    networks:
      - lab
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

volumes:
  kali-root:

networks:
  lab:
    name: xss-lab
    driver: bridge